### PR TITLE
Fix #4 - Added support for static and dynamic tick labels on chart axes

### LINKED ISSUE #4: Use non-Number values for data on StockLine chart type
I want to show the xKey as a string,but it's a number, i tried to modified it,but it doesn't work.

### PR DESCRIPTION
**Pull request by marzolfb**
Added support for both static and dynamic tick labels on the StockLine chart as discussed in #4.

Summary of changes:
- In Axis.js, removed references to the `labelComponent` option property and replaced it with a new option property: `labelFunction`. Use of this new option allows the chart creator to define a custom function to display dynamically generated tick labels displayed on an axis
- Added two new StockLine charts to the example app - one demonstrating the use of static tick labels and one demonstrating dynamic tick labels
- Added basic jest snapshot tests for more charts:
   - StockLine - basic
   - StockLine - using static tick values
   - StockLine - using dynamic tick values
   - Scatterplot (added this as a non-StockLine chart to see if changes to Axis.js would impact it differently than StockLine)
   
   (Not completely happy with mocking and Jest tests but something in place to compare to is better than nothing at all)

### CODE REVIEW

File: example/src/stockline/StockLineChartDynamicTickLabels.js [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+        duration: 200
+      },
+      axisX: {
+        showAxis: true,
+        showLines: true,
+        showLabels: true,
+        showTicks: true,
+        zeroAxis: false,
+        orient: 'bottom',
+        tickValues: [],
```
Comment (katscott) [inline example/src/stockline/StockLineChartDynamicTickLabels.js]: Is the empty array required to be present or can it be cleaned up? (just curious)

Comment (marzolfb) [inline example/src/stockline/StockLineChartDynamicTickLabels.js]: I was actually just being consistent with StockLineChartBasic. I haven't actually tested if there is any break for removing the empty tickValues array from options. Hopefully there isn't and it is just there for documentation purposes showing that the option is available.
